ls -lh ../js/jquery-3.3.1.min.js
ls -lh ../js/default.js
ls -lh ../js/jquery-migrate-3.0.1.min.js
ls -lh ../css/bootstrap.min.css
ls -lh ../plugins/cubeportfolio/css/cubeportfolio.min.css
ls -lh ../plugins/font-awesome/css/font-awesome.min.css
ls -lh ../plugins/bootstrap-toastr/toastr.min.css
ls -lh ../plugins/css/layout.min.css
ls -lh ../css/components.min.css
ls -lh ../css/plugins.min.css
ls -lh ../css/default.min.css
ls -lh ../plugins/select2/css/select2.min.css
ls -lh ../js/bootstrap.min.js
ls -lh ../plugins/cubeportfolio/js/jquery.cubeportfolio.min.js
ls -lh ../plugins/bootstrap-toastr/toastr.min.js
ls -lh ../js/jquery.smooth-scroll.min.js
ls -lh ../plugins/jquery-slimscroll/jquery.slimscroll.min.js
ls -lh ../js/jquery.blockui.min.js
ls -lh ../js/components.min.js
ls -lh ../js/app.min.js
ls -lh ../js/jquery.mobile.touch.min.js
ls -lh ../js/quick-nav.min.js
ls -lh ../plugins/js/app.min.js
ls -lh ../plugins/js/layout.min.js
ls -lh ../plugins/select2/js/select2.full.min.js
ls -lh ../plugins/bootstrap-sweetalert/sweetalert.min.css
ls -lh ../plugins/bootstrap-sweetalert/sweetalert.min.js
ls -lh ../js/favoritos.js
ls -lh ../js/estatistica.js
ls -lh ../js/publicidade.js
ls -lh ../css/style.css